default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  # <<: *default
  # database: db/production.sqlite3
  adapter: postgresql
  database: railway
  username: postgres
  password: U2CCumJBJQ2BUcKPP8gc
  host: containers-us-west-63.railway.app
  port: 5780
  pool: 5
